# Generated by Django 2.2.9 on 2020-01-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Title',
            new_name='title',
        ),
    ]
