# Generated by Django 2.2.9 on 2020-01-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='sloggo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.TextField(default='summart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
