# Generated by Django 2.2.9 on 2020-01-07 17:24

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('events', '0006_forthcomingevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_images', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
