# Generated by Django 2.2.9 on 2020-01-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='forthcomingevents',
            name='limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
