# Generated by Django 2.2.9 on 2020-01-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_forthcomingevents_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='forthcomingevents',
            name='style',
            field=models.CharField(choices=[('SIMPLE', 'Simple'), ('FANCY', 'Fancy')], default='SIMPLE', max_length=10),
        ),
    ]
